---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: Addon
metadata:
  name: helloworld
  labels:
    kubeaddons.mesosphere.io/name: helloworld
  annotations:
    catalog.kubeaddons.mesosphere.io/certification: '["certified"]'
    catalog.kubeaddons.mesosphere.io/addon-revision: "0.1.1-1"
    appversion.kubeaddons.mesosphere.io/helloworld: "0.1.1"
spec:
  kubernetes:
    minSupportedVersion: v1.16.3
  cloudProvider:
    - name: aws
      enabled: true
    - name: azure
      enabled: true
    - name: docker
      enabled: true
    - name: none
      enabled: true
  chartReference:
    chart: helloworld
    repo: https://charts.helloworld.io
    version: 0.1.1
    values: |
      ---
      name:
        helloworld
